# Generated by Django 2.1.7 on 2019-05-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscribete', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inscribete',
            new_name='Registracion',
        ),
    ]
