# Generated by Django 2.1.7 on 2019-05-04 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0021_remove_subtemas_curso'),
        ('inscribete', '0002_auto_20190503_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='registracion',
            name='curso',
            field=models.ForeignKey(blank=True, default=None, help_text='El profesor del curso', on_delete=django.db.models.deletion.CASCADE, to='curso.Curso'),
        ),
    ]
