# Generated by Django 2.1.7 on 2019-04-04 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20190404_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='popularidad',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
