# Generated by Django 2.1.7 on 2019-04-10 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_categorias_popularidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['popularidad']},
        ),
        migrations.AlterField(
            model_name='categorias',
            name='popularidad',
            field=models.PositiveSmallIntegerField(default=20000, help_text='Elija un numero para ordenar los cursos mediante la popularidad.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
