# Generated by Django 2.1.7 on 2019-04-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_auto_20190410_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='curso/<django.db.models.fields.CharField>/imagen/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='video',
            field=models.FileField(blank=True, upload_to='curso/<django.db.models.fields.CharField>/video/'),
        ),
    ]
