# Generated by Django 2.1.7 on 2019-04-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_auto_20190417_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='curso/imagen/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='video',
            field=models.FileField(blank=True, upload_to='curso/video/'),
        ),
    ]
