# Generated by Django 2.1.7 on 2019-04-18 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_auto_20190417_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2000)),
                ('subtemas', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='curso.Subtemas')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='temas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.Temas'),
        ),
    ]
