# Generated by Django 2.1.7 on 2019-04-18 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0010_auto_20190418_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtemas',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.Curso'),
        ),
    ]
