# Generated by Django 2.1.7 on 2019-04-18 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0011_subtemas_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtemas',
            name='curso',
        ),
        migrations.AddField(
            model_name='temas',
            name='subtema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.Subtemas'),
        ),
    ]
