# Generated by Django 2.1.7 on 2019-04-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0012_auto_20190418_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.SlugField(blank=True, help_text='La sección del curso si este lleva una sección.')),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='seccion',
        ),
        migrations.AddField(
            model_name='seccion',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.Curso'),
        ),
    ]
