# Generated by Django 2.1.7 on 2019-04-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0013_auto_20190418_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='tieneSeccion',
        ),
        migrations.AddField(
            model_name='seccion',
            name='tieneSeccion',
            field=models.BooleanField(default=False, help_text='Marque el encasillado si este curso tiene una sección', verbose_name='tiene sección'),
        ),
    ]
