# Generated by Django 2.1.7 on 2019-04-18 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0015_auto_20190418_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='diasdelasemana',
            name='curso_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.Curso'),
        ),
    ]
