# Generated by Django 2.1.7 on 2019-04-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0016_diasdelasemana_curso_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diasdelasemana',
            name='curso_a',
        ),
    ]
