# Generated by Django 2.1.7 on 2019-04-19 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0019_auto_20190419_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temas',
            name='subtema',
        ),
        migrations.AddField(
            model_name='subtemas',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.Curso'),
        ),
    ]
