# Generated by Django 2.1.7 on 2019-04-11 01:58

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contenidoDelWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=900, verbose_name='Contenido')),
                ('pagina', models.CharField(max_length=30)),
            ],
            managers=[
                ('contenido', django.db.models.manager.Manager()),
            ],
        ),
    ]
